

import java.util.*;

/**
 *
 * @author Usuario
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    private CEDict ced;
    private Segmenter segmenter;

    public UI() {
        initComponents();
        ced = new CEDict("dictionary/cedict_ts.u8");
        segmenter=new Segmenter(Segmenter.SIMP, true);
        inputBox.setEditable(true);
        outputBox.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputBox = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextPane();
        btnProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(inputBox);

        jScrollPane2.setViewportView(outputBox);

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnProcesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        outputBox.setText("");
        proc(inputBox.getText());
    }//GEN-LAST:event_btnProcesarActionPerformed

    public void proc(String str) {
        String segmentado = segmenter.segmentLine(str, " ");
        for (String value : segmentado.split(" ")) {
            CEWord word = ced.getSIMPLIFIED(value);
            try {
                String currContent = (outputBox.getText().isEmpty()) ? "" : outputBox.getText() + "\n";
                outputBox.setText(currContent + word.FULL);
            } catch (NullPointerException ex) {
                altProc(value);
            }
        }
    }

    public void altProc(String str) {
        Set<String> dictSIMPLIFIED = ced.getDictSIMPLIFIED();
        String replace = null;
        for (String string : dictSIMPLIFIED) {
            if ((str).startsWith(string)) {
                String firstChar = string;
                CEWord word = ced.getSIMPLIFIED(firstChar);
                try {
                    String currContent = (outputBox.getText().isEmpty()) ? "" : outputBox.getText() + "\n";
                    outputBox.setText(currContent + word.FULL);
                } catch (NullPointerException ex) {
                    altProc(firstChar);
                }
                String lastChar = (str).replace(string, "");
                word = ced.getSIMPLIFIED(lastChar);
                try {
                    String currContent = (outputBox.getText().isEmpty()) ? "" : outputBox.getText() + "\n";
                    outputBox.setText(currContent + word.FULL);
                } catch (NullPointerException ex) {
                    altProc(lastChar);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UI ui = new UI();
                ui.setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JTextPane inputBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane outputBox;
    // End of variables declaration//GEN-END:variables
}
